# Generated by Django 4.1 on 2022-09-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_otp_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
    ]
