# Generated by Django 4.1 on 2022-09-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_remove_profile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='درباره من'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='sutdent-prof.png', null=True, upload_to='profile_image', verbose_name='عکس کاربر'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
