# Generated by Django 4.1 on 2022-09-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_alter_category_options_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='patern',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Children', to='Article.category', verbose_name='زیر دسته'),
        ),
    ]
