# Generated by Django 4.1 on 2022-09-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0005_category_patern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='patern',
            new_name='parent',
        ),
    ]
