# Generated by Django 4.1 on 2022-09-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_rename_patern_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__id', '-created'], 'verbose_name': 'دسته بندی ', 'verbose_name_plural': 'دسته بندی  ها'},
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('p', 'منتشر شده')], default=1, max_length=1, verbose_name='وضعیت'),
            preserve_default=False,
        ),
    ]
