# Generated by Django 4.1 on 2022-09-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0008_alter_article_status_alter_category_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
