# Generated by Django 4.1 on 2022-09-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0009_remove_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='images/articls', verbose_name='تصویر'),
            preserve_default=False,
        ),
    ]
