# Generated by Django 4.1 on 2022-09-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0013_remove_article_views_article_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
    ]
