# Generated by Django 4.1 on 2022-09-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0014_remove_article_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPAddress',
        ),
    ]
